package seo.dale.practice.aws.dynamodb;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.Date;

@DynamoDBTable(tableName = Config.TABLE_NAME)
@Data
public class Number {
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBRangeKey
    private Date date;

    private String value;
}
