package seo.dale.practice.aws.dynamodb.self.first;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.Date;

@DynamoDBTable(tableName = Config.TABLE_NAME)
@Data
public class Item {
    @DynamoDBHashKey
    private String id;

    @DynamoDBRangeKey
    @DynamoDBAutoGeneratedTimestamp(strategy=DynamoDBAutoGenerateStrategy.CREATE)
    private Date created;

    @DynamoDBAttribute
    private Long expired;
}
